openapi: 3.0.0
info:
  title: My Workout App API
  description: A simple API documented with Swagger
  version: 1.0.0

servers:
  - url: http://localhost:4000

paths:
  /api/workouts:
    get:
      summary: Get all workouts
      responses:
        '200':
          description: A list of all workouts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workout'

    post:
      summary: Create a new workout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkoutInput'
      responses:
        '200':
          description: Workout created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '400':
          description: Bad request

  /api/workouts/{id}:
    get:
      summary: Get a single workout by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Workout found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '404':
          description: Workout not found

    delete:
      summary: Delete a workout by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Workout deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '404':
          description: Workout not found

    patch:
      summary: Update a workout by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkoutInput'
      responses:
        '200':
          description: Workout updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '404':
          description: Workout not found

components:
  schemas:
    Workout:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        reps:
          type: integer
        load:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    WorkoutInput:
      type: object
      required:
        - title
        - reps
        - load
      properties:
        title:
          type: string
        reps:
          type: integer
        load:
          type: integer
