openapi: 3.0.0
info:
  title: My Workout App API
  description: A simple API documented with Swagger
  version: 1.0.0

servers:
  - url: http://localhost:4000

tags:
  - name: Workout
    description: Operations related to workout management
  - name: Auth
    description: User authentication (signup and login)

paths:
  /api/workouts:
    get:
      tags:
        - Workout
      summary: Get all workouts
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of all workouts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workout'

    post:
      tags:
        - Workout
      summary: Create a new workout
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkoutInput'
      responses:
        '200':
          description: Workout created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '400':
          description: Bad request

  /api/workouts/{id}:
    get:
      tags:
        - Workout
      summary: Get a single workout by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Workout found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '404':
          description: Workout not found

    delete:
      tags:
        - Workout
      summary: Delete a workout by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Workout deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '404':
          description: Workout not found

    patch:
      tags:
        - Workout
      summary: Update a workout by ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkoutInput'
      responses:
        '200':
          description: Workout updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workout'
        '404':
          description: Workout not found

  /api/user/signup:
    post:
      tags:
        - Auth
      summary: Sign up a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: User signed up successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Invalid input or user already exists

  /api/user/login:
    post:
      tags:
        - Auth
      summary: Login an existing user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Invalid credentials

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Workout:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        reps:
          type: integer
        load:
          type: integer
        user_id:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    WorkoutInput:
      type: object
      required:
        - title
        - reps
        - load
      properties:
        title:
          type: string
        reps:
          type: integer
        load:
          type: integer

    UserInput:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
          format: password

    AuthResponse:
      type: object
      properties:
        email:
          type: string
        token:
          type: string
